# .yarnrc.yml
nodeLinker: node-modules
installConfig:
  pnp: false
  defaultLanguage: "node"
  cacheFolder: ".yarn/cache"
  yarnPath: ".yarn/releases/yarn-berry.js"
  linkedModules: true
  ignorePlatform: []
  preferredCacheFolder: ".yarn/cache"
  immutablePatterns:
    - "**/node_modules/**"
    - "**/.yarn/**"
    - "**/.yarnrc.yml"
  enableImmutableCache: true
  # add the following line to list the supported architectures
  supportedArchitectures:
    - "linux-x64"
    - "win32-x64"
