services:
  client:
    container_name: frontend
    build:
      dockerfile: ./client/Dockerfile
    volumes: 
      - ./client/src:/usr/src/app/src
    ports:
      - 80:80
    networks:
      finance:
        aliases:
          - frontend
  server:
    container_name: backend
    build:
      dockerfile: ./server/Dockerfile
    volumes: 
      - ./server:/usr/src/app/server
    ports:
      - 5000:5000
    networks:
      finance:
        aliases:
          - backend
  postgresql:
    container_name: postgresql
    build:
      dockerfile: ./database/Dockerfile
    volumes:
      - ./database:/usr/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      finance:
        aliases:
          - postgresql
      
networks:
  finance:
    driver: bridge
