version: "1.5"

services:
  client:
    container_name: fe
    build:
      dockerfile: ./client/Dockerfile
    volumes: 
      - ./client/src:/usr/src/app/src
    ports:
      - 80:80
    environment:
      - VITE_BASE_URL=http://localhost:3000/api
    networks:
      finance:
        aliases:
          - fe 
  server:
    container_name: backend
    build:
      dockerfile: ./Dockerfile
    volumes: 
      - ./src:/usr/src/app/src
      - ./prisma:/usr/src/app/prisma
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432/finance
      - PORT=3000
      - CHATGPT_SECRET_KEY=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
    networks:
      finance:
        aliases:
          - backend
    depends_on:
      - postgresql
  postgresql:
    container_name: postgres
    build:
      dockerfile: ./database/Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=finance
    volumes:
      - ./database/data:/usr/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      finance:
        aliases:
          - postgresql
          - db
networks:
  finance:
    driver: bridge
