version: "1.5"

services:
  client:
    container_name: fe
    build:
      dockerfile: ./client/Dockerfile
    volumes: 
      - ./client/src:/usr/src/app/src
    ports:
      - 80:80
    networks:
      finance:
        aliases:
          - fe 
  server:
    container_name: backend
    build:
      dockerfile: ./server/Dockerfile
    volumes: 
      - ./server/src:/usr/src/app/src
      - ./server/prisma:/usr/src/app/prisma
    ports:
      - 3000:3000
    # command: ["sh", "-c", "until nc -z postgresql 5432; do sleep 1; done && yarn prisma migrate dev && yarn run dev"]
    networks:
      finance:
        aliases:
          - backend
    depends_on:
      - postgresql
  postgresql:
    container_name: postgres
    build:
      dockerfile: ./database/Dockerfile
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=finance
    volumes:
      - ./database/data:/usr/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      finance:
        aliases:
          - postgresql
          - db
networks:
  finance:
    driver: bridge
