export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const ADD_WALLET = 'ADD_WALLET';
export const DELETE_WALLET = 'DELETE_WALLET';
export const GET_WALLETS = 'GET_WALLETS';
export const GET_INCOME = 'GET_INCOME';
export const GET_EXPENSES = 'GET_EXPENSES';
export const GET_BALANCE = 'GET_BALANCE';
export const GET_TOTAL_INCOME = 'GET_TOTAL_INCOME';
export const GET_TOTAL_EXPENSES = 'GET_TOTAL_EXPENSES';
export const GET_TOTAL_BALANCE = 'GET_TOTAL_BALANCE';
export const SET_LOADING = 'SET_LOADING';

